[[redirects]]
  from = "/"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/portal"
  to = "/client-portal.html"
  status = 200

[[redirects]]
  from = "/portal/"
  to = "/client-portal.html"
  status = 200
